together:
  app:
    name: app
    host: 127.0.0.1
    port: 8080
    path: app
    version: v1
  page:
    page-no-name: 
    page-size-name: 
    page-size: 10
  
    
server:
  address: ${together.app.host}
  port: ${together.app.name}
  context-path: /${together.app.version}/${together.app.path}